// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: stackoverflow/gunk/v1/answere/all.proto

package answerepb

import (
	reflect "reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stackoverflow_gunk_v1_answere_all_proto protoreflect.FileDescriptor

var file_stackoverflow_gunk_v1_answere_all_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f,
	0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x2f,
	0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x65, 0x70, 0x62, 0x42, 0x42, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x27, 0x73, 0x74, 0x61, 0x63,
	0x6b, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x3b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x65, 0x70, 0x62, 0x80, 0x01, 0x00, 0x88, 0x01, 0x00, 0x90, 0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8,
	0x01, 0x00, 0xf8, 0x01, 0x01, 0xd0, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stackoverflow_gunk_v1_answere_all_proto_goTypes = []interface{}{}
	file_stackoverflow_gunk_v1_answere_all_proto_depIdxs = []int32{
		0, // [0:0] is the sub-list for method output_type
		0, // [0:0] is the sub-list for method input_type
		0, // [0:0] is the sub-list for extension type_name
		0, // [0:0] is the sub-list for extension extendee
		0, // [0:0] is the sub-list for field type_name
	}
)

func init() { file_stackoverflow_gunk_v1_answere_all_proto_init() }
func file_stackoverflow_gunk_v1_answere_all_proto_init() {
	if File_stackoverflow_gunk_v1_answere_all_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stackoverflow_gunk_v1_answere_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stackoverflow_gunk_v1_answere_all_proto_goTypes,
		DependencyIndexes: file_stackoverflow_gunk_v1_answere_all_proto_depIdxs,
	}.Build()
	File_stackoverflow_gunk_v1_answere_all_proto = out.File
	file_stackoverflow_gunk_v1_answere_all_proto_rawDesc = nil
	file_stackoverflow_gunk_v1_answere_all_proto_goTypes = nil
	file_stackoverflow_gunk_v1_answere_all_proto_depIdxs = nil
}
